return {
  -- {
  --   "L3MON4D3/LuaSnip",
  --   opts = {
  --     region_check_events = "CursorMoved",
  --   },
  --   keys = function()
  --     return {}
  --   end,
  -- },
  -- {
  --   "rafamadriz/friendly-snippets",
  --   config = function()
  --     vim.tbl_map(function(type)
  --       require("luasnip.loaders.from_" .. type).lazy_load()
  --     end, { "vscode", "snipmate", "lua" })
  --     require("luasnip.loaders.from_vscode").lazy_load({
  --       paths = {
  --         "./snippets",
  --       },
  --     })
  --   end,
  -- },
}
